FROM centos

RUN yum install python36 -y
RUN yum install python36-devel -y
RUN yum install python3-pip -y

RUN pip3 install --upgrade pip

RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install tensorflow==2.1.0
RUN pip3 install keras=2.3.1

RUN mkdir /code
VOLUME /code